MegaBite/Clients/Web/Sugar/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using MegaBite.Clients.Web.Sugar.Areas.HelpPage.ModelDescriptions;
using MegaBite.Clients.Web.Sugar.Areas.HelpPage.Models;

namespace MegaBite.Clients.Web.Sugar.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

MegaBite/Clients/Web/Sugar/Controllers/RecipeController.cs
using BulletTime.Operational.Dependency;
using MegaBite.Clients.Web.Sugar.Binders;
using MegaBite.Data.Provider.AzureBlob;
using MegaBite.Domain.Contracts;
using MegaBite.Domain.Model;
using MegaBite.Operational.Error;
using Microsoft.WindowsAzure.Storage;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MegaBite.Clients.Web.Sugar.Controllers
{

    public class RecipeController : ControllerCommon
    {
        #region Properties
        /// <summary>
        /// Gets the Recipe business.
        /// </summary>
        /// <remarks>The concrete implementation is resolved using the DependencyFactory which in turn uses Unity to resolve the implementation.</remarks>
        /// <value>
        /// The Recipe business.
        /// </value>
        protected IRecipeBusiness RecipeBusiness
        {
            get
            {
                return DependencyFactory.GetContainer()
                                        .Resolve<IRecipeBusiness>("RecipeBusiness");
            }
        }

        #endregion

        #region Methods
        // GET: Recipe
        public ActionResult Index()
        {
            List<Recipe> recipes = new List<Recipe>();
            try
            {
                recipes = RecipeBusiness.GetAll();
            }
            catch
            {
                throw new MBException("Could not call the business layer to get all.");
            }
            return View(recipes);
        }

        // GET: Recipe/Details/5
        public ActionResult Details(Guid id)
        {
            Recipe recipe;
            try
            {
                recipe = RecipeBusiness.GetById(id);
            }
            catch
            {
                throw new MBException("Could not call business layer to get by Id.");
            }
            return View(recipe);
        }

        // GET: Recipe/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recipe/Create
        [HttpPost]
        public ActionResult Create([ModelBinder(typeof(RecipeBinder))]Recipe recipe)
        {
            try
            {
                recipe.Operation = Operation.Create;
                
                RecipeBusiness.SaveRecipe(recipe);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recipe/Edit/5
        public ActionResult Edit(Guid id)
        {
            Recipe recipe;
            try
            {
                recipe = RecipeBusiness.GetById(id);
            }
            catch
            {
                throw new MBException("Could not call business layer to edit.");
            }
            return View(recipe);
        }

        // POST: Recipe/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] Recipe recipe)
        {

            try
            {
                recipe.Operation = Operation.Update;
                RecipeBusiness.SaveRecipe(recipe);
            }
            catch (Exception ex)
            {
                //If error in below layers, return that error to the view.
                return HandleError(ex, recipe);
            }

            return RedirectToAction("Index");
        }

        // GET: Recipe/Delete/5
        public ActionResult Delete(Guid id)
        {
            Recipe recipe;
            try
            {
                recipe = RecipeBusiness.GetById(id);
            }
            catch
            {
                throw new MBException("Could not call business layer to get by id.");
            }
            return View(recipe);
        }

        // POST: Recipe/Delete/5
        [HttpPost]
        public ActionResult Delete(Recipe recipe)
        {
            try
            {
                RecipeBusiness.DeleteRecipe(recipe);

                return RedirectToAction("Index");
            }
            catch
            {
                throw new MBException("Could not delete recipe.");
            }
        }
    }
    #endregion

}

MegaBite/Clients/Web/Sugar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - MegaBite</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MegaBite", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>*@
                    <li>@Html.ActionLink("Recipes", "Index", "Recipe")</li>
                    <li>@Html.ActionLink("Create a Recipe", "Create", "Recipe")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Danielle Fenske</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>